### ISSUE TITLE
Loading issues.. Animation issues 

### ISSUE THREAD

**Issue by saranpmanoj** [CODE-73/vestido-ecommerce#106]
https://github.com/user-attachments/assets/547b0057-e9eb-4fda-abdf-f888e1c35e4b

**Comment by FathimaSayeeda** [comment]
[Screencast from 24-08-24 10:00:56 AM IST.webm](https://github.com/user-attachments/assets/3c840d42-a063-4569-84d8-0ebb024600d5)


Corrected using SSR
