### ISSUE TITLE
Carousel Button Flickerings

### ISSUE THREAD

**Issue by saranpmanoj** [CODE-73/vestido-ecommerce#107]
https://github.com/user-attachments/assets/3ee537d2-7608-443b-b5d4-c47f0e19e452

#bug

**Comment by fahimalizain** [comment]
@saranpmanoj Please test this on the latest deployment?
https://beta.vestidonation.com

**Comment by FathimaSayeeda** [comment]
[Screencast from 24-08-24 10:22:11 AM IST.webm](https://github.com/user-attachments/assets/c7b947ae-53cc-4653-9d91-770a11ce7570)
